description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
      with:
        cache: true
        require-lockfile: true
        runtime: node@24.21.0
    - run: which -a node npm npx; node --version; npm --version; ls -la "$(dirname "$(which node)")" | head
      shell: bash
  using: composite
